---
version: '3'
services:
  postgresql:
    image: postgres:11.3
    ports:
    - 5432
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
    - postgresql_data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    ports:
      - 9000
    environment:
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
    entrypoint: sh
    command: -c 'mkdir -p /data/buda && minio server /data'
    volumes:
      - minio_data:/data

volumes:
  postgresql_data:
  minio_data:
