---
version: '3'
services:
  postgresql:
    image: postgres:11.3
    environment:
      - POSTGRES_USER=sheardemo
      - POSTGRES_PASSWORD=sheardemo
      - POSTGRES_DB=sheardemo
    ports:
      - "5432:5432"
    volumes:
    - postgresql_data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    ports:
      - 9000
    environment:
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
    entrypoint: sh
    command: -c 'mkdir -p /data/buda && minio server /data'
    volumes:
      - minio_data:/data

volumes:
  postgresql_data:
  minio_data:
